# Autogenerated with SMOP version 0.23
# main.py ../matlab/curl_on_triangle.m -o ../python/curl_on_triangle.py
from __future__ import division,print_function
import numpy as np
import datatools as dt
import scipy as sp
import matplotlib.pyplot as plt
import os
np.set_printoptions(precision=8,suppress=True)


name = 'kitimat3_128'
grid = 'kitimat3'
dim = '2d'

directory='/home/moflaher/Desktop/workspace_python/figures/timeseries/curl/' + grid + '_' + name + '_' + dim + '/'
if not os.path.exists(directory):
    os.makedirs(directory)

if 1 == 1:

    fileDir='/media/moflaher/My Book/kitimat3_timetests/kitimat3_128_0/output/'
    data = dt.loadnc(fileDir,None,'2D')
    data = dt.ncdatasort(data)
   


    #region, passage, passageP = regions('kitimat3') # nargout=3
    #nidx, uvidx = get_indexs(nodell, uvnodell, region, trinodes) # nargout=2



if 1 == 1:
    a, b = data['ua'].shape # nargout=2
    curl = np.zeros((b, a))
    z_vec = np.zeros((1,a)).T
    ua_in = np.hstack([data['ua'],z_vec]).T
    va_in = np.hstack([data['va'],z_vec]).T
    for i in np.arange(0,len(data['uvnodell'])):
        e1 = data['nbe'][i, 0]
        e2 = data['nbe'][i, 1]
        e3 = data['nbe'][i, 2]
        dudy = np.dot(data['a2u'][i, 0], ua_in[i, :]) + np.dot(data['a2u'][i, 1], ua_in[e1, :]) + np.dot(data['a2u'][i, 2], ua_in[e2, :]) + np.dot(data['a2u'][i, 3], ua_in[e3, :])
        dvdx = np.dot(data['a1u'][i, 0], va_in[i, :]) + np.dot(data['a1u'][i, 1], va_in[e1, :]) + np.dot(data['a1u'][i, 2], va_in[e2, :]) + np.dot(data['a1u'][i, 3], va_in[e3, :])
        curl[i,:] = dvdx - dudy



del ua_in, va_in, z_vec


cminmax=np.percentile(curl.reshape(1,-1).T,[5,95])


for i in xrange(100,400):
        plt.tripcolor(data['trigrid'],facecolors=curl[:,i],vmin=cminmax[0],vmax=cminmax[1])
        plt.colorbar()
        plt.title('Curl')
        plt.xlabel('Longitude (degrees)')
        plt.ylabel('Latitude (degrees)')
        plt.savefig(directory + 'curl_step_' + str(i).zfill(4) + '.png',dpi=600)
        plt.close()
        print i







        

